### 1. NumPy Arrays
Learn:
- What arrays are
- How to create them

### 2. Create Arrays

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


### 3. Array Properties

In [3]:
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Data type:", b.dtype)

Shape: (2, 2)
Dimensions: 2
Data type: int64


### 4. Special Arrays

In [4]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 2))
identity = np.eye(3)

print(zeros)
print(ones)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 5. Practice Task

In [5]:
# Create a 3x3 matrix of random numbers
task = np.random.rand(3, 3)
print(task)

[[0.36183862 0.58012711 0.56397647]
 [0.23195851 0.59424202 0.05469141]
 [0.30423733 0.5905081  0.11718976]]
