### 1. Arithmetic

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


### 2. Scalar Ops

In [4]:
print(a + 10)
print(a * 2)

[11 12 13]
[2 4 6]


### 3. Aggregations

In [5]:
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Max:", a.max())

Sum: 6
Mean: 2.0
Max: 3


### 4. Practice

In [6]:
# Find mean of [5,10,15]
arr = np.array([5, 10, 15])
print(arr.mean())

10.0
