### 1. Linear Algebra for Machine Learning

### 2. imorts

In [1]:
import numpy as np

### 3. Dot Product

In [2]:
a = np.array([1, 2])
b = np.array([3, 4])

dot = np.dot(a, b)
print("Dot product:", dot)

Dot product: 11


### 4. Matrix Multiplication

In [3]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.matmul(A, B)
print(result)

[[19 22]
 [43 50]]


### 5. Transpose

In [4]:
print(A.T)

[[1 3]
 [2 4]]


### 6. Determinant

In [5]:
det = np.linalg.det(A)
print("Determinant:", det)

Determinant: -2.0000000000000004


### 7. Inverse

In [6]:
inv = np.linalg.inv(A)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


### 8. ML Insight (Linear Regression Idea)

y = Xw

Where:
- X = features
- w = weights

### 9. Practice

In [7]:
# Multiply two matrices
A = np.array([[2, 0],
              [1, 3]])

B = np.array([[1, 2],
              [3, 4]])

print(np.matmul(A, B))

[[ 2  4]
 [10 14]]
