Critical for:

- data splitting
- simulations
- ML randomness

### 1.  Random Sampling in NumPy

### 2. Imports

In [1]:
import numpy as np

### 3. Random Numbers

In [2]:
print(np.random.rand(3))       # uniform
print(np.random.randn(3))      # normal

[0.6612894  0.43474657 0.42872786]
[ 0.26002417 -0.70683149  0.19055762]


### 4. Random Integers

In [3]:
print(np.random.randint(0, 10, size=5))

[8 0 7 9 8]


### 5. Shuffle

In [8]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

print(arr)

[4 2 3 1 5]


### 6. Sampling

In [9]:
sample = np.random.choice([10, 20, 30, 40], size=3)
print(sample)

[10 30 30]


### 7. Reproducibility

In [10]:
np.random.seed(42)

print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


### 8. Practice

In [11]:
# Generate 5 random numbers between 0 and 1
print(np.random.rand(5))

[0.59865848 0.15601864 0.15599452 0.05808361 0.86617615]
