### 1. Matrices for Machine Learning

### 2. What is a Matrix?

In [1]:
import numpy as np

X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(X)

[[1 2]
 [3 4]
 [5 6]]


👉 Think:

- rows = samples
- columns = features

### 3. Transpose

In [2]:
print(X.T)

[[1 3 5]
 [2 4 6]]


### 4. Matrix Multiplication

In [3]:
A = np.array([[1, 2]])
B = np.array([[3], [4]])

print(np.matmul(A, B))

[[11]]


👉 ML meaning:

- predictions = X · weights

### 5. System of Equations

Ax = b

In [4]:
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 6])

x = np.linalg.solve(A, b)
print(x)

[1.8 1.4]


### 6. Determinant

👉 tells if matrix is invertible

In [5]:
A = np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))

-2.0000000000000004


### 7. Inverse

In [6]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]
